# app.py
import streamlit as st
from dotenv import load_dotenv
import os
# Import your custom modules
from src.rag import get_rag_context

# Load environment variables
load_dotenv()

st.title("LucidNA: Genomic Risk Analysis")

# Input for the Ngrok URL (generated by the Colab notebook)
api_url = st.sidebar.text_input("Paste Ngrok URL here")

gene_input = st.text_input("Enter Variant (e.g., BRCA1)")

if st.button("Analyze"):
    st.write("Fetching RAG context...")
    # Call your RAG function
    context = get_rag_context(gene_input)
    st.write(context)
    
    # Here you would add the call to the Ngrok API